### ISSUE TITLE
Stats are off

### ISSUE THREAD

**Issue by xXBuilderBXx** [Kiritsu/OsuSharp#4]
This wrapper is returning https://i.imgur.com/mM40CfK.png but the osu website shows https://i.imgur.com/yB6FcdY.png Source: https://osu.ppy.sh/users/11696417

**Comment by xXBuilderBXx** [comment]
Nvm looks like the default game mode for that url is set to osu!catch and not osu 😡

**Comment by Kiritsu** [comment]
What endpoint/method did you use and how did you use it? The wrapper should return by default standard's stats mode
