### ISSUE TITLE
Add replay writer

### ISSUE THREAD

**Issue by Kiritsu** [Kiritsu/OsuSharp#7]
It would be nice to add a way to get the .osr file from the content returned by the API in replay endpoint.

**Comment by NaamloosDT** [comment]
👀 

look who I found c:

**Comment by NaamloosDT** [comment]
I'll take a look

**Comment by NaamloosDT** [comment]
Alright so I managed to read osr files but the real issue is writing them, I haven't managed to write an osr back to a readable format yet (for both osu and my own parser)

**Comment by NaamloosDT** [comment]
well it' (mostly) readable but there's an issue at the end of the file, might be a problem on my end (out of index exceptions etc)

**Comment by Kiritsu** [comment]
Thanks a lot @NaamloosDT!
